import type { VersionEntry } from "./VersionEntry";

// Base Version Entry
// {
//     version: "",
//     commit: "",
//     date: "",
//     description: "",
//     additions: [""],
//     reworks: [""],
//     removals: [""],
//   },

export const VERSION_HISTORY: VersionEntry[] = [
  {
    version: "v2.0.1",
    commit: "latest",
    date: "May 4th, 2026",
    description:
      "Added a way to keep track of the version history of this project (that isn't on GitHub). Updated README with all of this information.",
    additions: [
      "Version Entry template",
      "Version History file",
      "History Page",
    ],
    reworks: ["App", "README"],
    removals: [],
  },
  {
    version: "v2.0.0",
    commit: "6c62a6c",
    date: "May 4th, 2026",
    description:
      "Reformatted Playwright Tests to have one for just loading pages, and one for running through all the branches in an adventure. Added an any alignment to Alignment. Added a GameContext to hold the Player's Initiative score, and revamped the whole Fight System to have different components for the fight, and show all the enemies and allies (combatants) on a battlefield grid, and show their HP trackers with a statblock revealer button as well. Added some handy functions that will allow me to change up the base Statblocks for variety.",
    additions: [
      "Game Context",
      "Game Provider",
      "Guard",
      "Combatant",
      "Create Combatant",
      "Play Initiative component",
      "Battlefield Grid component",
      "Combatant Card component",
      "Display Statblock component",
      "Add Language function",
      "Add Race function",
      "Change Name function",
      "Tests for add Langauge/Race and Change Name",
      "Race Enum",
    ],
    reworks: [
      "Playwright Tests separation",
      "Alignment",
      "Fight Node Type",
      "Fight Page",
      "Dice Roller",
      "Test Adventure",
    ],
    removals: [],
  },
  {
    version: "v1.7.0",
    commit: "b5869c5",
    date: "May 1st, 2026",
    description:
      "Separated out all my Story Components into different classes, and had Fight Page use my dice roller. Added a function to calculate modifiers, and added Unalignment as an Alignment option. Added a new Action template, and updated the Statblock template and Goblin objects, and added the Wolf object.",
    additions: [
      "Story Page",
      "Story Components",
      "Calculate Modifier",
      "Calculate Modifier Test",
      "Action template",
      "Wolf",
    ],
    reworks: ["Fight Page", "Alignment", "Statblock", "Goblin"],
    removals: ["Story Node"],
  },
  {
    version: "v1.6.0",
    commit: "1353f8f",
    date: "May 1st, 2026",
    description:
      "Added some comments between 2014 and 2024 edition differences, and added some new Weapon objects",
    additions: [
      "Martial Ranged Weapons objects",
      "Players Handbook Guns objects",
    ],
    reworks: ["Martial Melee Weapons objects"],
    removals: [],
  },
  {
    version: "v1.5.0",
    commit: "1ca30a8",
    date: "May 1st, 2026",
    description: "Added new Weapon objects",
    additions: ["Martial Melee Weapons objects"],
    reworks: [],
    removals: [],
  },
  {
    version: "v1.4.0",
    commit: "fc0ec9b",
    date: "April 30th, 2026",
    description: "Added new Armor objects",
    additions: ["Heavy Armor objects"],
    reworks: [],
    removals: [],
  },
  {
    version: "v1.3.0",
    commit: "2ad947e",
    date: "April 30th, 2026",
    description: "Added new Armor objects",
    additions: ["Light Armor objects", "Medium Armor objects"],
    reworks: [],
    removals: [],
  },
  {
    version: "v1.2.1",
    commit: "cba6dc3",
    date: "April 30th, 2026",
    description: "Swapped constructor for consistency",
    additions: [],
    reworks: ["Shield object"],
    removals: [],
  },
  {
    version: "v1.2.0",
    commit: "6ec9659",
    date: "April 30th, 2026",
    description:
      "Reworked the testing system, fixed some imports, and created a new Constructor for weapons and armor",
    additions: ["Simple Plus Num Constructor for Weapons and Shields"],
    reworks: ["Testing System", "Shield object"],
    removals: [],
  },
  {
    version: "v1.1.0",
    commit: "b2dfa44",
    date: "April 30th, 2026",
    description:
      "Added Simple Ranged Weapons, and changed Monster Manual file structure so there will be a package for each starting letter for organization.",
    additions: ["Simple Ranged Weapons"],
    reworks: ["Monster Manual project structure"],
    removals: [],
  },
  {
    version: "v1.0.0",
    commit: "9463a2e",
    date: "April 30th, 2026",
    description:
      "Started the project by moving my js code into ts. Added a lot of different base classes to allow my code to have extendable code, and all the base information to run D&D.",
    additions: [
      "CI Pipeline",
      "AdventureCard",
      "README System",
      "Spell template",
      "Adventure Loader",
      "Ability Score Enum",
      "Alignment Enum",
      "Creature Type Enum",
      "Languages Enum",
      "Senses Enum",
      "Size Enum",
      "Skills Enum",
      "Statblock template",
      "Legendary Statblock template",
      "Spellcaster Statblock template",
      "Item template",
      "Jest and Playwright testing",
      "Condition Enum",
      "Damage Statblock template",
      "Dice template",
      "Dice Constructor",
      "Dice Roller",
      "Dice Constructor + Roller Tests",
      "Cost template",
      "Coin Enum",
      "Armor template",
      "Armor Constructor",
      "Shield object",
      "Weapon template",
      "Weapon Constuctor",
      "Attack Damage template",
      "Weapon Properties Enum",
      "Weapon Damage Constructor",
      "Spear object",
      "Weapon Constructor Test",
      "Armor Constructor Test",
      "Goblin object",
      "Simple Melee Weapons objects",
      "Weapon Mastery Enum",
      "Cost Constructor",
      "Npm run configurations",
      "Home Page",
      "Fight Page",
      "Adventure Page",
    ],
    reworks: ["File structure", "Import system"],
    removals: [],
  },
];
